11. Skapa en ny dataframe ”regions” som innehåller sammansatt data per region(Region_2013_label). Lägg till en ny kolumn som innehåller ”Rate_per_10000_population” fast för hela regionen.

Återkoppling: Alright, #11 is incorrect. "Regions" should concern every region. That is, we want all the data in them to be groupby'd. Then calculate the "Rate per 10000", as in, number of victimizations per 10000 population.

In [21]:
import numpy as np
import pandas as pd

In [35]:
df = pd.read_csv('assults.csv', skipinitialspace = True)

In [38]:
df

,Index,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label
0,1,514102,Auckland Central West,550,15900,346,6.6,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
1,2,573101,Willis Street-Cambridge Terrace,447,8300,539,10.3,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region
2,3,529700,Hamilton Central,380,3170,"1,199",22.9,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region
3,4,514103,Auckland Central East,375,13250,283,5.4,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
4,5,591500,Cathedral Square,305,570,"5,351",102.3,22,Christchurch,Main urban area,60,Christchurch City,13,Canterbury Region
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,2016,506653,Riverhead,0,3510,-,-,502,Rural (Incl.some Off Shore Islands),Rural area,76,Auckland,2,Auckland Region
2016,2017,610601,Grasmere,0,3590,-,-,24,Invercargill,Main urban area,75,Invercargill City,15,Southland Region
2017,2018,536513,Bethlehem East,0,3590,-,-,9,Tauranga,Main urban area,23,Tauranga City,4,Bay of Plenty Region
2018,2019,574302,Te Kainga,0,4020,-,-,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region
2019,2020,527007,Horsham Downs,0,5440,-,-,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region

In [39]:
df.columns

Index(['Index', 'Area_unit_2013_code', 'Area_unit_2013_label',
       'Victimisations_calendar_year_2015', 'Population_mid_point_2015',
       'Rate_per_10000_population ', 'Rate_ratio_NZ_average_rate ',
       'Urban_area_2013_code', 'Urban_area_2013_label', 'Urban_area_type',
       'Territorial_authority_area_2013_code',
       'Territorial_authority_area_2013_label', 'Region_2013_code',
       'Region_2013_label'],
      dtype='object')

In [40]:
df.columns = df.columns.str.replace(' ', '')

In [41]:
df.columns

Index(['Index', 'Area_unit_2013_code', 'Area_unit_2013_label',
       'Victimisations_calendar_year_2015', 'Population_mid_point_2015',
       'Rate_per_10000_population', 'Rate_ratio_NZ_average_rate',
       'Urban_area_2013_code', 'Urban_area_2013_label', 'Urban_area_type',
       'Territorial_authority_area_2013_code',
       'Territorial_authority_area_2013_label', 'Region_2013_code',
       'Region_2013_label'],
      dtype='object')

In [42]:
regions = df[['Region_2013_label','Rate_per_10000_population']]
regions

         Region_2013_label Rate_per_10000_population
0          Auckland Region                       346
1        Wellington Region                       539
2           Waikato Region                     1,199
3          Auckland Region                       283
4        Canterbury Region                     5,351
...                    ...                       ...
2015       Auckland Region                      -
2016      Southland Region                      -
2017  Bay of Plenty Region                      -
2018     Wellington Region                      -
2019        Waikato Region                      -

[2020 rows x 2 columns]

In [43]:
regions['Rate_per_10000_population'] = regions['Rate_per_10000_population'].str.replace(',', '.')

C:\Users\mimmi\AppData\Local\Temp\ipykernel_20324\3691871004.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  regions['Rate_per_10000_population'] = regions['Rate_per_10000_population'].str.replace(',', '.')

In [47]:
regions['Rate_per_10000_population'] = regions['Rate_per_10000_population'].replace('-   ', np.nan).astype(float)
print(regions.dtypes)

Region_2013_label             object
Rate_per_10000_population    float64
dtype: object

C:\Users\mimmi\AppData\Local\Temp\ipykernel_20324\977937739.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  regions['Rate_per_10000_population'] = regions['Rate_per_10000_population'].replace('-   ', np.nan).astype(float)

In [50]:
regions

         Region_2013_label  Rate_per_10000_population
0          Auckland Region                    346.000
1        Wellington Region                    539.000
2           Waikato Region                      1.199
3          Auckland Region                    283.000
4        Canterbury Region                      5.351
...                    ...                        ...
2015       Auckland Region                        NaN
2016      Southland Region                        NaN
2017  Bay of Plenty Region                        NaN
2018     Wellington Region                        NaN
2019        Waikato Region                        NaN

[2020 rows x 2 columns]

In [49]:
regions_grouped = regions.groupby('Region_2013_label').Rate_per_10000_population.mean().reset_index()
regions_grouped

           Region_2013_label  Rate_per_10000_population
0        Area Outside Region                        NaN
1            Auckland Region                  53.140211
2       Bay of Plenty Region                  61.718843
3          Canterbury Region                  51.161138
4            Gisborne Region                  86.350000
5         Hawke's Bay Region                  73.572917
6   Manawatu-Wanganui Region                  59.763303
7         Marlborough Region                  81.789474
8              Nelson Region                  51.187875
9           Northland Region                  49.993679
10              Otago Region                  50.730500
11          Southland Region                  62.537037
12           Taranaki Region                  42.197917
13             Tasman Region                  37.894737
14            Waikato Region                  51.802333
15         Wellington Region                  49.356190
16         West Coast Region                  55.740741